# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: savings.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'savings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsavings.proto\x12\x07savings\"f\n\x1a\x43reateGoalOperationRequest\x12\x0f\n\x07goal_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x16\n\x0eoperation_type\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\"\xd2\x01\n\x15GoalOperationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07goal_id\x18\x03 \x01(\t\x12\x16\n\x0eoperation_type\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x01\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x16\n\x0e\x66\x61ilure_reason\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\t\x12\x14\n\x0cprocessed_at\x18\t \x01(\t\x12\x11\n\ttransport\x18\n \x01(\t2l\n\x0eSavingsService\x12Z\n\x13\x43reateGoalOperation\x12#.savings.CreateGoalOperationRequest\x1a\x1e.savings.GoalOperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'savings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEGOALOPERATIONREQUEST']._serialized_start=26
  _globals['_CREATEGOALOPERATIONREQUEST']._serialized_end=128
  _globals['_GOALOPERATIONRESPONSE']._serialized_start=131
  _globals['_GOALOPERATIONRESPONSE']._serialized_end=341
  _globals['_SAVINGSSERVICE']._serialized_start=343
  _globals['_SAVINGSSERVICE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
