# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\"%\n\x12UserSummaryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"X\n\x13UserSummaryResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06income\x18\x02 \x01(\x01\x12\x0f\n\x07\x65xpense\x18\x03 \x01(\x01\x12\x0f\n\x07\x62\x61lance\x18\x04 \x01(\x01\x32i\n\x12TransactionService\x12S\n\x0eGetUserSummary\x12\x1f.transaction.UserSummaryRequest\x1a .transaction.UserSummaryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERSUMMARYREQUEST']._serialized_start=34
  _globals['_USERSUMMARYREQUEST']._serialized_end=71
  _globals['_USERSUMMARYRESPONSE']._serialized_start=73
  _globals['_USERSUMMARYRESPONSE']._serialized_end=161
  _globals['_TRANSACTIONSERVICE']._serialized_start=163
  _globals['_TRANSACTIONSERVICE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
